### ISSUE TITLE
Array in POST produces warning

### ISSUE THREAD

**Issue by sharykin** [mjmunger/php-ant#1]
When POST request contains an array it produces
Warning: mb_check_encoding() expects parameter 1 to be string, array given in /home/tcsfiles/www/includes/classes/WebRequest.class.php on line 51

**Comment by mjmunger** [comment]
The WebRequest class checks for certain types of encoding, but was not setup to deal with arrays as variables. I have added a function that uses array_map() to check array elements in the case that an array has been passed.
